services:
  ripe-atlas:
    image: docker.io/jamesits/ripe-atlas:latest
    restart: always
    environment:
      RXTXRPT: "yes"
    volumes:
      - "/etc/ripe-atlas:/etc/ripe-atlas"
      - "/run/ripe-atlas:/run/ripe-atlas"
      - "/var/spool/ripe-atlas:/var/spool/ripe-atlas"
    cap_drop:
      - ALL
    cap_add:
      - NET_RAW
      # required for tini
      - KILL
      # required for `setpriv` to work
      - SETUID
      - SETGID
      # required for the entrypoint script to auto-fix the permissions of the directories
      - CHOWN
      - FOWNER
      - DAC_OVERRIDE
    mem_limit: "64000000000"
    mem_reservation: 64m
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: json-file
      options:
         max-size: 10m
    # If possible, use host networking to avoid double NAT
    # network_mode: "host"
    networks:
      - default
    # Maybe needed when your host OS is old enough, see https://github.com/Jamesits/docker-ripe-atlas/issues/19
    # security_opt:
    #   - seccomp:unconfined

networks:
  default:
    enable_ipv6: true
